source("renv/activate.R")
# load automatically required libraries
library(flexdashboard)
library(shiny)
library(shinythemes)
library(shinydashboard)
library(shinyWidgets)
library(leaflet)
library(leaflet.extras)
library(leafsync)
library(sf)
library(tidyverse)
library(RColorBrewer)
library(shinyjs)
library(htmltools)
library(raster)
